### ISSUE TITLE
Is this MCU or SFU?

### ISSUE THREAD

**Issue by hiteshjoshi** [rriverak/gogo#5]

**Comment by rriverak** [comment]
Hey,
yeah its a Software MCU. 

It uses [gStreamer pipelines](https://github.com/rriverak/gogo/tree/master/internal/gst) to mix the individual videos into [a simple grid](https://github.com/rriverak/gogo/blob/61363256b386d7e380a665ad8513c2a183de3542/internal/gst/pipelines.go#L26). The audio is also mixed into one Audio Stream. All Video GroupCall participants upload their video / audio via WebRTC, the server mixed all streams together and streams the result back to all participants. This is encapsulated in a thing that is called [Session](https://github.com/rriverak/gogo/blob/61363256b386d7e380a665ad8513c2a183de3542/internal/rtc/session.go#L30) here.

That behavior can save bandwidth compared to SFU Video Group Calls. 

I haven't worked on the project for a longer time and currently don't have time for it. 
But I think the gStreamer + golang C Bridge  + pion/webrtc implementation is a good place to start.
